using Communityclinic;
using System;
using System.Data;
using System.Data.SqlClient;
using static Communityclinic.Models.PatientModels;

namespace Communityclinic
{
    internal class PatientDAL
    {
        // Adds a new patient
        public void AddPatient(Patient patient)
        {
            using (SqlConnection conn = DatabaseHelper.GetConnection())
            {
                // The INSERT query does not include ID because it is auto-increment
                string query = @"INSERT INTO Patient 
                                (Name, DateOfBirth, Age, Address, PhoneNumber, EmailAddress, Gender, Allergies, History, Medications)
                                VALUES 
                                (@Name, @DateOfBirth, @Age, @Address, @PhoneNumber, @EmailAddress, @Gender, @Allergies, @History, @Medications);
                                SELECT SCOPE_IDENTITY();"; // returns auto-generated ID

                using (SqlCommand cmd = new SqlCommand(query, conn))
                {
                    cmd.Parameters.AddWithValue("@Name", patient.Name);
                    cmd.Parameters.AddWithValue("@DateOfBirth", patient.DateOfBirth);
                    cmd.Parameters.AddWithValue("@Age", patient.Age);
                    cmd.Parameters.AddWithValue("@Address", patient.Address);
                    cmd.Parameters.AddWithValue("@PhoneNumber", patient.PhoneNumber);
                    cmd.Parameters.AddWithValue("@EmailAddress", patient.EmailAddress);
                    cmd.Parameters.AddWithValue("@Gender", patient.Gender);
                    cmd.Parameters.AddWithValue("@Allergies", patient.Allergies);
                    cmd.Parameters.AddWithValue("@History", patient.History);
                    cmd.Parameters.AddWithValue("@Medications", patient.Medications);

                    conn.Open();

                    // ExecuteScalar returns the new ID generated by the database
                    int newId = Convert.ToInt32(cmd.ExecuteScalar());

                }
            }
        }

        // This updates an existing patient
        public void UpdatePatient(Patient patient)
        {
            using (SqlConnection conn = DatabaseHelper.GetConnection())
            {
                string query = @"UPDATE Patient 
                                 SET Name=@Name, 
                                     DateOfBirth=@DateOfBirth, 
                                     Age=@Age, 
                                     Address=@Address, 
                                     PhoneNumber=@PhoneNumber, 
                                     EmailAddress=@EmailAddress, 
                                     Gender=@Gender, 
                                     Allergies=@Allergies, 
                                     History=@History, 
                                     Medications=@Medications
                                 WHERE Id=@Id"; // This updates the specific patient by ID

                using (SqlCommand cmd = new SqlCommand(query, conn))
                {
       
                    cmd.Parameters.AddWithValue("@Name", patient.Name);
                    cmd.Parameters.AddWithValue("@DateOfBirth", patient.DateOfBirth);
                    cmd.Parameters.AddWithValue("@Age", patient.Age);
                    cmd.Parameters.AddWithValue("@Address", patient.Address);
                    cmd.Parameters.AddWithValue("@PhoneNumber", patient.PhoneNumber);
                    cmd.Parameters.AddWithValue("@EmailAddress", patient.EmailAddress);
                    cmd.Parameters.AddWithValue("@Gender", patient.Gender);
                    cmd.Parameters.AddWithValue("@Allergies", patient.Allergies);
                    cmd.Parameters.AddWithValue("@History", patient.History);
                    cmd.Parameters.AddWithValue("@Medications", patient.Medications);

                    conn.Open();
                    int rowsAffected = cmd.ExecuteNonQuery();

                    if (rowsAffected == 0)
                    {
                        throw new Exception("No patient updated. Make sure the Id is correct.");
                    }
                }
            }
        }

        // Retrieves all patients
        public DataTable GetPatients()
        {
            using (SqlConnection conn = DatabaseHelper.GetConnection())
            {
                string query = "SELECT * FROM Patient";

                using (SqlDataAdapter da = new SqlDataAdapter(query, conn))
                {
                    DataTable dt = new DataTable();
                    da.Fill(dt);
                    return dt;
                }
            }
        }
    }
}